### ISSUE TITLE
Vapoursynth?

### ISSUE THREAD

**Issue by Selur** [pinterf/RemoveDirt#1]
Any chance for a Vapoursynth port of this plugin, as the existin Vapoursynth port seems to be totally instable. :(

**Comment by pinterf** [comment]
Not much :(
As I remember I was looking into backporting the VS port (this is why I still have this forked repo) but for some reason I chose the harder but surely working way of porting the original one.

**Comment by Selur** [comment]
Thanks for the reply, at least now I know where I stand. :)

**Comment by pinterf** [comment]
I guess it would take a at most a week incl. learning curve. I've seen VS things but if v3 and not interface v4, but it wouldn't be that hard. I have quite a few things in my queue but his can be a challenge. If no one ports it, ping me periodically.

**Comment by Selur** [comment]
Ping. ;)

**Comment by pinterf** [comment]
This period is too short :)

**Comment by Selur** [comment]
Just the occasional ping: Ping :)

**Comment by DmitryVN** [comment]
> This period is too short :)

+1 Ping!

We are waiting for a response. :)

**Comment by pinterf** [comment]
So no one has ported it yet. I'm sad. Presently - since months - I'm full of office jobs, sorry.

**Comment by Selur** [comment]
(just a reminder ;))
Hope you are doing well and life isn't treating you bad.

**Comment by Selur** [comment]
Just the occasional 'ping' so this does not get lost. No rush on my side (I can work around it by using Avisynth.).
So whenever you find time and motivation. :)

**Comment by Selur** [comment]
Happy New Year. 
Ping :)

**Comment by pinterf** [comment]
Happy New Year! New year, A New Hope. :)

**Comment by Selur** [comment]
Ping, not giving up :) Hope, you are well.

**Comment by Selur** [comment]
Ping :)

**Comment by Selur** [comment]
Time for a 'Ping' :)

**Comment by Selur** [comment]
'Ping'
